package com.primaloptima.scribe.util

import com.primaloptima.scribe.util.model.AppTheme
import com.primaloptima.scribe.util.model.ThemeColors

object DefaultThemes {

    val all: List<AppTheme> = listOf(
        AppTheme(
            id = "obsidian", name = "Obsidian", isDark = true, builtIn = true,
            colors = ThemeColors(
                background      = "#121214",
                surfaceLowest   = "#161619",
                surface         = "#1E1E22",
                surfaceRaised   = "#26262B",
                surfaceOverlay  = "#303036",
                text            = "#F4F4F6",
                mutedText       = "#A1A1AA",
                subtleText      = "#8E8E93",
                accent          = "#E4E4E7",
                secondary       = "#B4B4BB",
                tertiary        = "#8E8E93",
                success         = "#4ADE80",
                warning         = "#FBBF24",
                error           = "#F87171",
                specialHighlight= "#FEF08A",
                accentMuted     = "#27272A",
                selection       = "#3F3F46",
                border          = "#2C2C32",
                borderSubtle    = "#232328",
                borderProminent = "#8E8E93",
                dialogueText    = "#FEF08A",
                monologueText   = "#D4D4D8",
                headingText     = "#FFFFFF",
                toolbar         = "#1E1E22",
                toolbarText     = "#F4F4F6"
            ),
            fontFamily = "sans", fontSize = 17, lineHeight = 1.68f,
            letterSpacing = 0.1f, paragraphSpacing = 14,
            paddingHorizontal = 24, paddingVertical = 20, maxWidth = 720
        ),
        AppTheme(
            id = "midnight", name = "Midnight Blue", isDark = true, builtIn = true,
            colors = ThemeColors(
                background      = "#0B111A",
                surfaceLowest   = "#0F1722",
                surface         = "#141D2B",
                surfaceRaised   = "#1C2739",
                surfaceOverlay  = "#243248",
                text            = "#EDF2F7",
                mutedText       = "#94A3B8",
                subtleText      = "#788CA5",
                accent          = "#70AEFB",
                secondary       = "#B8A4F2",
                tertiary        = "#63D5D0",
                success         = "#55D18A",
                warning         = "#FFC857",
                error           = "#FF6B7A",
                specialHighlight= "#E7B85A",
                accentMuted     = "#1E314B",
                selection       = "#25436B",
                border          = "#1E2C40",
                borderSubtle    = "#182333",
                borderProminent = "#70AEFB",
                dialogueText    = "#FFD166",
                monologueText   = "#C3B1F7",
                headingText     = "#82BDFF",
                toolbar         = "#141D2B",
                toolbarText     = "#EDF2F7"
            ),
            fontFamily = "sans", fontSize = 17, lineHeight = 1.70f,
            letterSpacing = 0.15f, paragraphSpacing = 14,
            paddingHorizontal = 24, paddingVertical = 20, maxWidth = 720
        ),
        AppTheme(
            id = "focus", name = "Focus", isDark = true, builtIn = true,
            colors = ThemeColors(
                background      = "#000000",
                surfaceLowest   = "#080808",
                surface         = "#121212",
                surfaceRaised   = "#1A1A1A",
                surfaceOverlay  = "#242424",
                text            = "#F0F0F0",
                mutedText       = "#A3A3A3",
                subtleText      = "#737373",
                accent          = "#F1F5F9",
                secondary       = "#CBD5E1",
                tertiary        = "#94A3B8",
                success         = "#34D399",
                warning         = "#FBBF24",
                error           = "#F87171",
                specialHighlight= "#FCD34D",
                accentMuted     = "#1E293B",
                selection       = "#334155",
                border          = "#262626",
                borderSubtle    = "#1F1F1F",
                borderProminent = "#737373",
                dialogueText    = "#34D399",
                monologueText   = "#A3A3A3",
                headingText     = "#FFFFFF",
                toolbar         = "#121212",
                toolbarText     = "#F0F0F0"
            ),
            fontFamily = "mono", fontSize = 17, lineHeight = 1.72f,
            letterSpacing = 0f, paragraphSpacing = 14,
            paddingHorizontal = 26, paddingVertical = 22, maxWidth = 700
        ),
        AppTheme(
            id = "paper", name = "Paper", isDark = false, builtIn = true,
            colors = ThemeColors(
                background      = "#FAF8F5",
                surfaceLowest   = "#F2EFE9",
                surface         = "#FFFFFF",
                surfaceRaised   = "#FFFFFF",
                surfaceOverlay  = "#FFFFFF",
                text            = "#1C211E",
                mutedText       = "#4F5953",
                subtleText      = "#78847E",
                accent          = "#234B39",
                secondary       = "#34624D",
                tertiary        = "#43735B",
                success         = "#2E7D32",
                warning         = "#B45309",
                error           = "#C5221F",
                specialHighlight= "#B45309",
                accentMuted     = "#E4EDE7",
                selection       = "#CEE1D5",
                border          = "#DDD8D0",
                borderSubtle    = "#E6E1D9",
                borderProminent = "#234B39",
                dialogueText    = "#8C4318",
                monologueText   = "#3B5A4B",
                headingText     = "#143326",
                toolbar         = "#FFFFFF",
                toolbarText     = "#1C211E"
            ),
            fontFamily = "serif", fontSize = 18, lineHeight = 1.72f,
            letterSpacing = 0.2f, paragraphSpacing = 15,
            paddingHorizontal = 26, paddingVertical = 22, maxWidth = 720
        ),
        AppTheme(
            id = "sepia", name = "Sepia", isDark = false, builtIn = true,
            colors = ThemeColors(
                background      = "#F5EBD7",
                surfaceLowest   = "#EBDDC5",
                surface         = "#EFE3CB",
                surfaceRaised   = "#FAF2E3",
                surfaceOverlay  = "#FDF8EE",
                text            = "#322214",
                mutedText       = "#695038",
                subtleText      = "#8F7254",
                accent          = "#7C3F14",
                secondary       = "#6E4525",
                tertiary        = "#825736",
                success         = "#2E6B1D",
                warning         = "#9A4308",
                error           = "#A81818",
                specialHighlight= "#A85312",
                accentMuted     = "#DEC5A5",
                selection       = "#D7B992",
                border          = "#D6C1A4",
                borderSubtle    = "#DFCDAF",
                borderProminent = "#7C3F14",
                dialogueText    = "#9A4308",
                monologueText   = "#4E3722",
                headingText     = "#5F320C",
                toolbar         = "#EFE3CB",
                toolbarText     = "#322214"
            ),
            fontFamily = "serif", fontSize = 19, lineHeight = 1.75f,
            letterSpacing = 0.25f, paragraphSpacing = 16,
            paddingHorizontal = 28, paddingVertical = 24, maxWidth = 680
        ),
        AppTheme(
            id = "typewriter", name = "Typewriter", isDark = false, builtIn = true,
            colors = ThemeColors(
                background      = "#F7F7F8",
                surfaceLowest   = "#EDEDF0",
                surface         = "#FFFFFF",
                surfaceRaised   = "#FFFFFF",
                surfaceOverlay  = "#FFFFFF",
                text            = "#111113",
                mutedText       = "#48484F",
                subtleText      = "#71717A",
                accent          = "#000000",
                secondary       = "#27272A",
                tertiary        = "#3F3F46",
                success         = "#15803D",
                warning         = "#B45309",
                error           = "#B91C1C",
                specialHighlight= "#78350F",
                accentMuted     = "#E4E4E7",
                selection       = "#D4D4D8",
                border          = "#D4D4D8",
                borderSubtle    = "#E4E4E7",
                borderProminent = "#111113",
                dialogueText    = "#9A3412",
                monologueText   = "#48484F",
                headingText     = "#000000",
                toolbar         = "#FFFFFF",
                toolbarText     = "#111113"
            ),
            fontFamily = "mono", fontSize = 16, lineHeight = 1.80f,
            letterSpacing = 0f, paragraphSpacing = 14,
            paddingHorizontal = 24, paddingVertical = 20, maxWidth = 680
        )
    )

    fun findById(id: String): AppTheme = all.firstOrNull { it.id == id } ?: all.first()
}

